# Generated by Django 4.2.20 on 2025-04-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_link_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='link_posts',
            new_name='like_posts',
        ),
    ]
