# Generated by Django 4.2.20 on 2025-04-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('요청', '요청'), ('대기', '대기'), ('진행', '진행'), ('피드백', '피드백'), ('완료', '완료'), ('보류', '보류')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=200)),
                ('main_task', models.CharField(max_length=200)),
                ('sub_task', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
