# Generated by Django 4.2.20 on 2025-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='main_task',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_task',
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.CharField(default='미지정', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.CharField(default='직위미지정', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('요청', '요청'), ('대기', '대기'), ('진행', '진행'), ('피드백', '피드백'), ('완료', '완료'), ('보류', '보류')], max_length=20),
        ),
    ]
