# Generated by Django 4.2.20 on 2025-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_category_project_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('요청', '요청'), ('대기', '대기'), ('진행', '진행'), ('피드백', '피드백'), ('완료', '완료'), ('보류', '보류')], max_length=10),
        ),
    ]
